### ISSUE TITLE
load_model shouldn't return error when model can't be loaded to prevent emulator crashes

### ISSUE THREAD

**Issue by quinnanm** [cms-hls4ml/hls4mlEmulatorExtras#3]
load_model should return an exception, not a runtime error so that the CMSSW emulator does not crash if an incompatible model is loaded, but instead prints a warning and returns a false condition.
https://github.com/cms-hls4ml/hls4mlEmulatorExtras/blob/58f1ed7bf55a7ab74277035d83c419de7cbe28d3/src/hls4ml/emulator.cc#L16

As discussed in the PR comments here: https://github.com/cms-sw/cmssw/pull/44054

> Two more suggestions for [ModelLoader::load_model()](https://github.com/cms-hls4ml/hls4mlEmulatorExtras/blob/main/src/hls4ml/emulator.cc) for longer term (maybe these should go into some issue?)
> 
>1) It would be better to use a specific exception type instead of std::runtime_error, so that the caller-side catch would catch only these specific errors from load_model()
>2) It would be better to include the message from the dlerror() in the exception message in all cases

**Comment by artlbv** [comment]
@aloeliger @epalencia since you mentioned this in the other PR, could you provide some assistance with this issue? do you know of any examples we could reuse here for returning an exception?

**Comment by aloeliger** [comment]
Okay, if I am understanding correctly, this was the error gotten when trying to load a bad model:

```
Cannot load library: asdahjsdksjd.so: cannot open shared object file: No such file or directory
ERROR: failed to load model version asdahjsdksjd. Not evaluating condition!
A fatal system signal has occurred: segmentation violation
```

This is a bit trickier than just proper exception handling because this is a segfault, which is uncatchable, being an OS level error. Let me take a look at what happened.

**Comment by aloeliger** [comment]
I think what's happening here is that when the error is caught on bad model load, `model_lib_`:

https://github.com/cms-hls4ml/hls4mlEmulatorExtras/blob/58f1ed7bf55a7ab74277035d83c419de7cbe28d3/include/hls4ml/emulator.h#L26

 in the model loader still exists, but is a null pointer. Later (in AXO's current case) when the condition is returned out of the model loader is destroyed, and the destructor goes to attempt `dlclose` on `model_lib_`, and I would guess this is where the segfault happens:
 
 https://github.com/cms-hls4ml/hls4mlEmulatorExtras/blob/58f1ed7bf55a7ab74277035d83c419de7cbe28d3/src/hls4ml/emulator.cc#L11-L13
 
This is fixable by simply testing that the pointer is non null, but let me see if I can set CICADA up in such a way to recreate the error and then rig it to use a fixed model loader. This is going to take a second...

**Comment by aloeliger** [comment]
Okay. I have a fix. Hang on this is going to require some github maneuvering.

**Comment by aloeliger** [comment]
Fixed by https://github.com/cms-hls4ml/hls4mlEmulatorExtras/pull/4
